import React, { useState } from 'react';
import { Bot, ChevronDown, Loader2, MessageCircle, Send, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import './MarketChatbot.css';

const LANGUAGES = ['English', 'Hindi', 'Bengali', 'Marathi', 'Telugu', 'Tamil', 'Gujarati', 'Kannada', 'Malayalam', 'Punjabi', 'Odia'];
const ROLE_CONTENT = {
  FARMER: { greeting: 'Namaste! I can help you compare mandi prices, choose a sale window, find buyers and track payments.', suggestions: ['Should I sell my crop today?', 'How do I create a produce lot?', 'How can I get paid by UPI?'], quick: { 'How do I create a produce lot?': 'Open Produce lots from your farmer workspace, choose a crop and available quantity, add the quality grade, then publish the lot for buyers.', 'How can I get paid by UPI?': 'Open Payments, select the transaction, choose Pay by UPI and scan the displayed QR code. Keep the payment reference for your records.' } },
  SELLER: { greeting: 'Welcome! I can help you find suitable farmer lots, publish demand and manage offers and payments.', suggestions: ['How do I find matching farmer lots?', 'How do I publish buyer demand?', 'How do I make an offer?'], quick: { 'How do I find matching farmer lots?': 'Open Produce lots to filter by crop, grade, quantity and location. Open a lot to review provenance and submit a digital offer.', 'How do I publish buyer demand?': 'Open Buyer demand, add crop, required quantity, grade, delivery window and target price, then publish the requirement.', 'How do I make an offer?': 'Open a suitable farmer lot, enter your quantity and price per kg, review the total and submit the digital offer.' } }
};

export default function MarketChatbot() {
  const { user } = useAuth(); const roleContent = ROLE_CONTENT[user?.role] || ROLE_CONTENT.FARMER;
  const [open, setOpen] = useState(false); const [language, setLanguage] = useState('English'); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState([{ role: 'assistant', content: roleContent.greeting }]);
  const send = async (event) => {
    event?.preventDefault(); const text = input.trim(); if (!text || loading) return;
    const next = [...messages, { role: 'user', content: text }]; setMessages(next); setInput('');
    if (roleContent.quick[text]) { setMessages(current => [...current, { role: 'assistant', content: roleContent.quick[text] }]); return; }
    setLoading(true);
    try { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 8000); const response = await fetch('/api/ai/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: controller.signal, body: JSON.stringify({ messages: next, language, context: { role: user?.role, name: user?.name, state: user?.state } }) }); window.clearTimeout(timeout); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message || 'Chat is unavailable'); setMessages(current => [...current, { role: 'assistant', content: payload.answer }]); }
    catch (error) { setMessages(current => [...current, { role: 'assistant', content: error.name === 'AbortError' ? 'The assistant is taking longer than expected. Try a suggested question for an instant answer.' : `I couldn't connect right now. ${error.message}` }]); } finally { setLoading(false); }
  };
  const useSuggestion = (text) => { if (roleContent.quick[text]) setMessages(current => [...current, { role: 'user', content: text }, { role: 'assistant', content: roleContent.quick[text] }]); else setInput(text); };
  return <>{!open && <button className="market-chat-launcher" onClick={() => setOpen(true)} aria-label="Open market assistant"><MessageCircle size={21} /><span>Market Assistant</span></button>}{open && <section className="market-chat" aria-label="KhetSetu Market Assistant"><header><div className="market-chat-title"><span className="market-chat-icon"><Bot size={18} /></span><div><strong>Market Assistant</strong><small>{user?.name ? `For ${user.name}` : 'AI guidance for your next sale'}</small></div></div><button onClick={() => setOpen(false)} aria-label="Close chat"><X size={18} /></button></header><div className="market-chat-toolbar"><span>Reply language</span><label><select value={language} onChange={event => setLanguage(event.target.value)}>{LANGUAGES.map(item => <option key={item}>{item}</option>)}</select><ChevronDown size={14} /></label></div><div className="market-chat-suggestions">{roleContent.suggestions.map(item => <button key={item} type="button" onClick={() => useSuggestion(item)}>{item}</button>)}</div><div className="market-chat-messages">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`market-chat-message ${message.role}`}>{message.content}</div>)}{loading && <div className="market-chat-message assistant"><Loader2 className="market-chat-spin" size={15} /> Thinking…</div>}</div><form onSubmit={send}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask about your market…" aria-label="Message" /><button type="submit" disabled={!input.trim() || loading} aria-label="Send message"><Send size={17} /></button></form></section>}</>;
}
