import React, { useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { ClipboardList, Handshake, PackageCheck, Plus, ShieldCheck, WalletCards } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useGlobalState } from '../../context/GlobalStateContext';
import { COMMODITIES, getCommodityById } from '../../services/market/marketIntelligenceService';
import './BuyerWorkspace.css';

const screenForPath = (pathname) => pathname.split('/').pop() === 'buyer' ? 'overview' : pathname.split('/').pop();
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`;

export default function BuyerWorkspace() {
  const { pathname } = useLocation();
  const view = screenForPath(pathname);
  const { user } = useAuth();
  const { woolLots = [], buyerDemands = [], marketOffers = [], marketTransactions = [], publishBuyerDemand, submitOffer } = useGlobalState();
  const [message, setMessage] = useState('');
  const [demand, setDemand] = useState({ cropId: 'WHEAT', quantityKg: 1000, minGrade: 'A', maxPricePerKg: 31, deliveryLocation: 'Kota, Rajasthan' });
  const cropLots = woolLots.filter(lot => lot.cropId !== 'WOOL' && lot.status !== 'SOLD');
  const openDemands = buyerDemands.filter(item => item.status !== 'CLOSED');
  const pendingOffers = marketOffers.filter(item => item.status === 'PENDING' || item.status === 'COUNTERED');
  const buyerTransactions = marketTransactions.filter(item => !item.buyerId || item.buyerId === user?.id || item.buyerName === user?.name);
  const metrics = useMemo(() => ({ lots: cropLots.length, demands: openDemands.length, offers: pendingOffers.length, value: marketTransactions.reduce((sum, transaction) => sum + Number(transaction.grossValue || 0), 0) }), [cropLots.length, openDemands.length, pendingOffers.length, marketTransactions]);
  const announce = (text) => { setMessage(text); window.setTimeout(() => setMessage(''), 3500); };
  const postDemand = (event) => { event.preventDefault(); const crop = getCommodityById(demand.cropId); publishBuyerDemand({ buyerId: user?.id || 'BUYER-LOCAL', buyerName: user?.name || 'Buyer organisation', cropId: crop.id, cropName: crop.name, quantityRequired: Number(demand.quantityKg), minGrade: demand.minGrade, maxPricePerKg: Number(demand.maxPricePerKg), deliveryLocation: demand.deliveryLocation, status: 'OPEN', paymentTerms: 'UPI or bank payment on pickup milestone' }); announce(`${crop.name} demand published for farmer and FPO matching.`); };
  const offerLot = (lot) => { const price = Number(lot.askingPrice || 0); submitOffer({ lotId: lot.id, lotNumber: lot.lotNumber, sellerId: lot.sellerId, sellerName: lot.sellerName, buyerId: user?.id || 'BUYER-LOCAL', buyerName: user?.name || 'Buyer organisation', woolType: lot.woolType || lot.cropName, qualityGrade: lot.qualityGrade, offeredPricePerKg: price, quantityKg: Math.min(Number(lot.availableQuantity || lot.totalQuantity), 1000), totalGrossAmount: price * Math.min(Number(lot.availableQuantity || lot.totalQuantity), 1000), paymentTerms: 'UPI payment request at confirmed pickup', deliveryTerms: 'Collection coordinated through platform' }); announce(`Offer sent for ${lot.lotNumber}.`); };
  const card = { background: '#FFFFFF', border: '1px solid #E2E8E0', borderRadius: 14, padding: 18 };
  return <div className="buyer-workspace" style={{ padding: 'clamp(16px, 4vw, 32px)', maxWidth: 1320, margin: '0 auto' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap', marginBottom: 24 }}><div><p style={{ margin: 0, color: '#55705B', fontWeight: 700, fontSize: 13 }}>Buyer workspace</p><h1 style={{ margin: '4px 0 8px', fontSize: 'clamp(24px, 4vw, 32px)' }}>{view === 'overview' ? `Procurement overview, ${user?.name || 'Buyer'}` : view === 'demand' ? 'Publish procurement demand' : view === 'lots' ? 'Matched produce lots' : view === 'offers' ? 'Offers and negotiation' : 'Orders and payments'}</h1><p style={{ margin: 0, color: '#64748B' }}>Source the right crop, grade and volume with a documented payment trail.</p></div><div style={{ ...card, padding: '10px 14px', alignSelf: 'flex-start', color: '#166534', fontSize: 13 }}><ShieldCheck size={16} style={{ verticalAlign: 'middle', marginRight: 6 }}/>Credential records available</div></div>
    {message && <div style={{ background: '#EAF6E7', border: '1px solid #9BCE95', padding: 12, borderRadius: 10, color: '#215A27', marginBottom: 16 }}>{message}</div>}
    {view === 'overview' && <><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: 14, marginBottom: 20 }}>{[[ClipboardList, 'Open produce lots', metrics.lots], [Handshake, 'Active demand notices', metrics.demands], [PackageCheck, 'Negotiations', metrics.offers], [WalletCards, 'Trade value tracked', money(metrics.value)]].map(([Icon, title, value]) => <div key={title} style={card}><Icon size={20} color="#166534"/><div style={{ color: '#64748B', marginTop: 10, fontSize: 13 }}>{title}</div><strong style={{ fontSize: 24 }}>{value}</strong></div>)}</div><div style={card}><h2 style={{ marginTop: 0, fontSize: 18 }}>Next procurement actions</h2><p style={{ color: '#64748B' }}>Publish exact quality and volume requirements, then review farmer/FPO lots and send a digital offer. Accepted offers create a payment-ready transaction.</p></div></>}
    {view === 'demand' && <form onSubmit={postDemand} style={{ ...card, maxWidth: 720, display: 'grid', gap: 14 }}><label>Commodity<select value={demand.cropId} onChange={e => setDemand({ ...demand, cropId: e.target.value })}>{COMMODITIES.filter(c => c.id !== 'WOOL' && c.category !== 'FIBER').map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: 12 }}><label>Required quantity (kg)<input required min="1" type="number" value={demand.quantityKg} onChange={e => setDemand({ ...demand, quantityKg: e.target.value })}/></label><label>Maximum price (₹/kg)<input required min="1" type="number" value={demand.maxPricePerKg} onChange={e => setDemand({ ...demand, maxPricePerKg: e.target.value })}/></label></div><label>Minimum grade<select value={demand.minGrade} onChange={e => setDemand({ ...demand, minGrade: e.target.value })}><option>A+</option><option>A</option><option>B</option></select></label><label>Delivery location<input required value={demand.deliveryLocation} onChange={e => setDemand({ ...demand, deliveryLocation: e.target.value })}/></label><button className="btn-primary" type="submit"><Plus size={16}/> Publish buyer demand</button></form>}
    {view === 'lots' && <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 14 }}>{cropLots.map(lot => <div key={lot.id} style={card}><p style={{ margin: 0, color: '#64748B', fontSize: 12 }}>{lot.lotNumber}</p><h2 style={{ fontSize: 18, margin: '8px 0' }}>{lot.cropName || lot.woolType}</h2><p style={{ color: '#475569', fontSize: 13 }}>{lot.availableQuantity || lot.totalQuantity} kg · Grade {lot.qualityGrade || 'Pending'} · {lot.origin || 'Origin recorded'}</p><strong>{money(lot.askingPrice)}/kg</strong><button className="btn-primary" style={{ width: '100%', marginTop: 14 }} onClick={() => offerLot(lot)}>Send digital offer</button></div>)}</div>}
    {view === 'offers' && <div style={{ display: 'grid', gap: 12 }}>{pendingOffers.map(offer => <div key={offer.id} style={{ ...card, display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><strong>{offer.woolType}</strong><p style={{ margin: '6px 0 0', color: '#64748B', fontSize: 13 }}>{offer.lotNumber} · {offer.quantityKg} kg · Seller: {offer.sellerName}</p></div><div><strong>{money(offer.offeredPricePerKg)}/kg</strong><p style={{ margin: '6px 0 0', color: '#64748B', fontSize: 12 }}>{offer.status}</p></div></div>)}</div>}
    {view === 'payments' && <div style={{ display: 'grid', gap: 12 }}>{(buyerTransactions.length ? buyerTransactions : marketTransactions).map(transaction => <div key={transaction.id} style={{ ...card, display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><strong>{transaction.transactionNumber}</strong><p style={{ margin: '6px 0 0', color: '#64748B', fontSize: 13 }}>{transaction.woolType} · {transaction.quantityKg} kg · {transaction.deliveryStatus}</p></div><div><strong>{money(transaction.grossValue)}</strong><p style={{ margin: '6px 0 0', color: transaction.paymentStatus === 'PAID' ? '#166534' : '#9A6700', fontSize: 12 }}>{transaction.paymentStatus}</p></div></div>)}</div>}
  </div>;
}
