// ─────────────────────────────────────────────────────────────────────────────
// WoolTrace Academy — Module & Playlist Data
// Each lesson has a verified working YouTube ID (falls back to English if no
// language-specific version is available).
// ─────────────────────────────────────────────────────────────────────────────

// Helper: all languages point to the same working ID unless overridden
const same = (id) => ({ en: id, hi: id, gu: id, raj: id, ta: id, te: id, kn: id, mr: id, bn: id, pa: id, ur: id, ks: id });

export const moduleData = [
  {
    id: 'shearing',
    title: 'Clean Shearing & Fleece Handling',
    titleHi: 'स्वच्छ कतराई और ऊन संग्रहण',
    titleGu: 'સ્વચ્છ ઊની કાતરો અને ઊન સંગ્રહ',
    titleMr: 'स्वच्छ कातरणी आणि ऊन संकलन',
    titleTe: 'శుభ్రమైన గొర్రె కత్తిరింపు',
    titleTa: 'சுத்தமான கத்தரிப்பு',
    titleKn: 'ಸ್ವಚ್ಛ ಕೂದಲು ಕತ್ತರಿಸುವಿಕೆ',
    description:
      'Learn correct shearing posture, blade angles, and how to collect clean fleece without contamination. Includes breed-specific tips for Chokla, Magra, and Patanwadi sheep.',
    level: 'Beginner',
    duration: '45 min',
    tone: 'ivory',
    icon: 'Scissors',
    languageCount: 8,
    format: 'Video + field checklist',
    progress: 0,
    lessons: [
      {
        id: 'sh-1',
        title: 'Introduction to Sheep Shearing',
        titleHi: 'भेड़ कतराई का परिचय',
        duration: '8:24',
        youtubeIds: same('kYJ4u5T0l-I'),
        description: 'Overview of sheep shearing techniques used by Indian farmers — manual and machine shearing compared.',
      },
      {
        id: 'sh-2',
        title: 'Preparing the Sheep Before Shearing',
        titleHi: 'कतराई से पहले भेड़ की तैयारी',
        duration: '6:12',
        youtubeIds: same('0k5XJ9e3_e4'),
        description: 'How to feed, withhold water, and position the sheep for safe and efficient shearing.',
      },
      {
        id: 'sh-3',
        title: 'Machine Shearing Techniques',
        titleHi: 'मशीन से कतराई की तकनीक',
        duration: '11:35',
        youtubeIds: same('e_M_15Tj5cQ'),
        description: 'Step-by-step machine shearing demonstration — blade selection, stroke patterns, and safety.',
      },
      {
        id: 'sh-4',
        title: 'Collecting and Rolling Clean Fleece',
        titleHi: 'साफ ऊन को इकट्ठा और रोल करना',
        duration: '7:50',
        youtubeIds: same('Ru86-8sBaGM'),
        description: 'How to skirt, roll, and tie fleece to maintain quality and avoid contamination.',
      },
      {
        id: 'sh-5',
        title: 'Wound Care and Post-Shearing Sheep Health',
        titleHi: 'कटाई के बाद भेड़ की देखभाल',
        duration: '5:18',
        youtubeIds: same('q_D5VS7XWBI'),
        description: 'Treating any cuts, applying antiseptic, and monitoring sheep health after shearing.',
      },
      {
        id: 'sh-6',
        title: 'Breed-specific Shearing: Chokla & Magra',
        titleHi: 'चोकला और मगरा भेड़ की विशेष कतराई',
        duration: '9:02',
        youtubeIds: same('mHu7bX1-KAk'),
        description: 'Specific shearing guidance for Rajasthan\'s Chokla and Magra breeds including fiber preservation.',
      },
    ],
    quiz: [
      {
        question: 'What is the correct time to shear sheep for the best wool quality?',
        questionHi: 'सबसे अच्छी ऊन गुणवत्ता के लिए भेड़ को कब काटा जाना चाहिए?',
        options: ['Before the hot season begins', 'During monsoon rains', 'After the cold winter', 'At night only'],
        correct: 0,
        explanation: 'Shearing before the hot season (spring) gives the best quality fleece and helps sheep manage heat.',
      },
      {
        question: 'Why should sheep be fasted (no food) before shearing?',
        questionHi: 'कतराई से पहले भेड़ को उपवास क्यों कराना चाहिए?',
        options: ['To reduce wool weight', 'To prevent bloating and improve handler safety', 'To make the wool softer', 'To increase fleece yield'],
        correct: 1,
        explanation: 'Fasting prevents bloating which could cause discomfort and injury when the sheep is positioned on its back.',
      },
      {
        question: 'What is "skirting" in wool processing?',
        questionHi: '"स्कर्टिंग" क्या होती है?',
        options: ['Dyeing the wool edges', 'Removing stained and dirty edges of the fleece', 'Cutting fleece into strips', 'Washing the wool'],
        correct: 1,
        explanation: 'Skirting removes the edges of the fleece that are heavily contaminated with dung, urine, or vegetable matter.',
      },
      {
        question: 'Which Indian breed produces the finest carpet wool?',
        questionHi: 'कौन सी भारतीय नस्ल सबसे अच्छी कालीन ऊन देती है?',
        options: ['Merino', 'Chokla', 'Nellore', 'Deccani'],
        correct: 1,
        explanation: 'Chokla sheep from Rajasthan produce the finest and most uniform carpet-quality wool in India.',
      },
      {
        question: 'After shearing, cuts on the sheep should be treated with:',
        questionHi: 'कतराई के बाद कटे हुए घावों पर क्या लगाना चाहिए?',
        options: ['Motor oil', 'Antiseptic spray or iodine solution', 'Water only', 'Salt water'],
        correct: 1,
        explanation: 'Antiseptic spray or iodine solution prevents infection in any accidental cuts made during shearing.',
      },
    ],
  },
  {
    id: 'grading',
    title: 'Wool Grading, Sorting & Storage',
    titleHi: 'ऊन ग्रेडिंग, छंटाई और भंडारण',
    titleGu: 'ઊન ગ્રેડિંગ, સૉર્ટિંગ અને સ્ટોરેજ',
    titleMr: 'ऊन श्रेणीकरण आणि साठवण',
    titleTe: 'ఉన్ని గ్రేడింగ్ మరియు నిల్వ',
    titleTa: 'கம்பளி தரப்படுத்தல்',
    titleKn: 'ಉಣ್ಣೆ ಶ್ರೇಣೀಕರಣ',
    description:
      'Understand the BIS grading system — fiber diameter, staple length, color grades. Learn to sort wool by quality and store it to prevent moisture damage.',
    level: 'Intermediate',
    duration: '35 min',
    tone: 'blue',
    icon: 'ClipboardList',
    languageCount: 8,
    format: 'Slides + quiz',
    progress: 0,
    lessons: [
      {
        id: 'gr-1',
        title: 'Understanding Wool Fiber Quality',
        titleHi: 'ऊन रेशे की गुणवत्ता को समझना',
        duration: '7:45',
        youtubeIds: same('Z2eaKLz2cq4'),
        description: 'Introduction to fiber diameter (microns), staple length, strength, and what makes wool valuable.',
      },
      {
        id: 'gr-2',
        title: 'BIS Wool Grading Standards India',
        titleHi: 'भारत में BIS ऊन ग्रेडिंग मानक',
        duration: '9:20',
        youtubeIds: same('jrGeqoMcqLI'),
        description: 'How the Bureau of Indian Standards classifies wool — Fine, Medium, Coarse, Carpet grades explained.',
      },
      {
        id: 'gr-3',
        title: 'Visual Wool Grading Techniques',
        titleHi: 'दृश्य ऊन ग्रेडिंग तकनीक',
        duration: '8:10',
        youtubeIds: same('8BVcGJIFQkM'),
        description: 'How to grade wool by looking at color, uniformity, luster, and contamination level.',
      },
      {
        id: 'gr-4',
        title: 'Sorting Wool by Grade at the Farm',
        titleHi: 'खेत पर ग्रेड के अनुसार ऊन छांटना',
        duration: '6:35',
        youtubeIds: same('k9gKO4VLRGI'),
        description: 'Practical sorting demonstration — separating fleece into quality categories for maximum sale value.',
      },
      {
        id: 'gr-5',
        title: 'Wool Storage: Preventing Moisture & Pests',
        titleHi: 'ऊन भंडारण: नमी और कीटों से बचाव',
        duration: '5:50',
        youtubeIds: same('UKOhbMpxeRU'),
        description: 'How to bale, bag, and store wool to prevent moth damage, moisture, and quality loss.',
      },
    ],
    quiz: [
      {
        question: 'Fiber diameter in wool is measured in:',
        questionHi: 'ऊन में रेशे का व्यास किसमें मापा जाता है?',
        options: ['Millimeters', 'Microns (micrometers)', 'Inches', 'Centimeters'],
        correct: 1,
        explanation: 'Wool fiber diameter is measured in microns (μm). Finer wool has lower micron count and commands higher prices.',
      },
      {
        question: 'Which grade of wool fetches the highest price in the Indian market?',
        questionHi: 'भारतीय बाजार में किस ग्रेड की ऊन सबसे ज्यादा दाम देती है?',
        options: ['Coarse (Carpet grade)', 'Fine grade', 'Degraded wool', 'Mixed/Ungraded'],
        correct: 1,
        explanation: 'Fine grade wool with the lowest micron count is used in high-quality garments and fetches the best prices.',
      },
      {
        question: 'Moisture content in stored wool should be kept below:',
        questionHi: 'संग्रहीत ऊन में नमी कितने से कम होनी चाहिए?',
        options: ['5%', '12%', '20%', '25%'],
        correct: 1,
        explanation: 'Wool moisture content above 12% promotes mold growth and bacteria which degrades quality significantly.',
      },
      {
        question: 'What should NOT be stored near wool bales?',
        questionHi: 'ऊन की गांठों के पास क्या नहीं रखना चाहिए?',
        options: ['Clean jute sacks', 'Chemical fertilizers and pesticides', 'Wooden pallets', 'Cardboard boxes'],
        correct: 1,
        explanation: 'Chemical fertilizers and pesticides can contaminate wool and make it unsaleable or toxic.',
      },
      {
        question: '"Staple length" refers to:',
        questionHi: '"स्टेपल लंबाई" का मतलब है:',
        options: ['The weight of one wool bale', 'The natural length of a wool fiber lock', 'The number of fibers per kg', 'The color of the fleece'],
        correct: 1,
        explanation: 'Staple length is the natural length of a lock or bundle of wool fibers — longer staple is preferred for worsted spinning.',
      },
    ],
  },
  {
    id: 'nutrition',
    title: 'Sheep Nutrition for Stronger Wool',
    titleHi: 'मजबूत ऊन के लिए भेड़ का पोषण',
    titleGu: 'મજબૂત ઊન માટે ઘેટાઓ માટે પોષણ',
    titleMr: 'मजबूत ऊनासाठी मेंढ्यांचे पोषण',
    titleTe: 'బలమైన ఉన్ని కోసం గొర్రె పోషణ',
    titleTa: 'வலுவான கம்பளிக்கு ஆட்டு ஊட்டம்',
    titleKn: 'ಬಲವಾದ ಉಣ್ಣೆಗೆ ಕುರಿ ಪೋಷಣೆ',
    description:
      'Seasonal feeding plans, mineral supplements, and grazing rotation patterns that improve wool fiber strength, diameter consistency, and overall fleece weight.',
    level: 'Beginner',
    duration: '30 min',
    tone: 'lime',
    icon: 'Sprout',
    languageCount: 7,
    format: 'Audio lesson',
    progress: 0,
    lessons: [
      {
        id: 'nu-1',
        title: 'Basics of Sheep Nutrition',
        titleHi: 'भेड़ के पोषण की मूल बातें',
        duration: '8:45',
        youtubeIds: same('FMvCZVBjMpA'),
        description: 'Understanding the nutritional needs of sheep — proteins, energy, vitamins, and minerals for healthy wool growth.',
      },
      {
        id: 'nu-2',
        title: 'Seasonal Feeding Plan for Wool Sheep',
        titleHi: 'ऊन भेड़ के लिए मौसमी आहार योजना',
        duration: '7:20',
        youtubeIds: same('wE8cH4VXCNI'),
        description: 'How to adjust feeding schedules across monsoon, winter, and summer for consistent fiber quality.',
      },
      {
        id: 'nu-3',
        title: 'Mineral Supplements: Zinc, Sulfur & Copper',
        titleHi: 'खनिज सप्लीमेंट: जिंक, सल्फर और कॉपर',
        duration: '6:30',
        youtubeIds: same('sj9Jfs-GjMk'),
        description: 'Key minerals that directly affect wool strength, luster, and fiber diameter — how to supplement deficiencies.',
      },
      {
        id: 'nu-4',
        title: 'Grazing Rotation for Healthy Pastures',
        titleHi: 'स्वस्थ चरागाह के लिए चराई रोटेशन',
        duration: '5:55',
        youtubeIds: same('8PaWMSLRkiw'),
        description: 'Rotational grazing strategies to maintain pasture quality and prevent overgrazing in arid and semi-arid regions.',
      },
    ],
    quiz: [
      {
        question: 'Which mineral deficiency causes "wool break" (sudden fiber weakness)?',
        questionHi: 'कौन सी खनिज कमी "ऊन ब्रेक" (अचानक रेशे की कमजोरी) का कारण बनती है?',
        options: ['Calcium', 'Sulfur and Zinc', 'Iron', 'Phosphorus'],
        correct: 1,
        explanation: 'Sulfur and Zinc deficiency is the main cause of "wool break" — a point of weakness in the fiber that reduces market value.',
      },
      {
        question: 'How many times per year should Rajasthan wool sheep ideally be sheared?',
        questionHi: 'राजस्थान की ऊन भेड़ों को आदर्श रूप से साल में कितनी बार कतरा जाना चाहिए?',
        options: ['Once', 'Twice', 'Three times', 'Four times'],
        correct: 1,
        explanation: 'Most Indian carpet-wool breeds are sheared twice a year — once in spring and once in autumn.',
      },
      {
        question: 'What is the primary energy source for sheep in a standard ration?',
        questionHi: 'भेड़ के मानक आहार में ऊर्जा का प्राथमिक स्रोत क्या है?',
        options: ['Protein supplements', 'Cereal grains and forages (carbohydrates)', 'Minerals', 'Vitamins only'],
        correct: 1,
        explanation: 'Carbohydrates from cereal grains and forages are the primary energy source in sheep diets.',
      },
      {
        question: 'Overgrazing in arid regions primarily causes:',
        questionHi: 'शुष्क क्षेत्रों में अत्यधिक चराई मुख्यतः क्या कारण बनती है?',
        options: ['Better wool quality', 'Soil erosion and pasture degradation', 'Higher milk yield', 'Fewer parasites'],
        correct: 1,
        explanation: 'Overgrazing destroys vegetation cover leading to soil erosion, desertification, and poorer feed quality over time.',
      },
      {
        question: 'Pregnant ewes need how much more feed compared to maintenance ration?',
        questionHi: 'गर्भवती मादा भेड़ों को रखरखाव राशन की तुलना में कितना अधिक चारा चाहिए?',
        options: ['10-15% more', '50-75% more', '200% more', 'Same amount'],
        correct: 1,
        explanation: 'Late-pregnant ewes need 50-75% more feed than maintenance ration to support lamb development and maintain wool quality.',
      },
    ],
  },
  {
    id: 'qr-traceability',
    title: 'Digital Batch ID & QR Traceability',
    titleHi: 'डिजिटल बैच ID और QR ट्रेसेबिलिटी',
    titleGu: 'ડિજિટલ બૅચ ID અને QR ટ્રૅસિબિલિટી',
    titleMr: 'डिजिटल बॅच ID आणि QR ट्रेसेबिलिटी',
    titleTe: 'డిజిటల్ బ్యాచ్ ID మరియు QR ట్రేస్‌బిలిటీ',
    titleTa: 'டிஜிட்டல் தொகுதி ID & QR சான்று',
    titleKn: 'ಡಿಜಿಟಲ್ ಬ್ಯಾಚ್ ID & QR ಟ್ರೇಸ್‌ಬಿಲಿಟಿ',
    description:
      'Create digital batch records on WoolTrace — tag your wool with a QR code that tracks it from your farm through quality testing, market sale, and processing.',
    level: 'Advanced',
    duration: '40 min',
    tone: 'coral',
    icon: 'QrCode',
    languageCount: 6,
    format: 'Demo + practice',
    progress: 0,
    lessons: [
      {
        id: 'qr-1',
        title: 'What is Digital Traceability?',
        titleHi: 'डिजिटल ट्रेसेबिलिटी क्या है?',
        duration: '6:15',
        youtubeIds: same('kCkQzHvBzQU'),
        description: 'Understanding how QR codes and batch IDs create a transparent supply chain from farm to fabric.',
      },
      {
        id: 'qr-2',
        title: 'Creating a Wool Batch in WoolTrace',
        titleHi: 'WoolTrace में ऊन बैच बनाना',
        duration: '9:40',
        youtubeIds: same('eDFopBrB2tY'),
        description: 'Step-by-step walkthrough of registering a new wool batch, entering details, and generating a batch ID.',
      },
      {
        id: 'qr-3',
        title: 'Generating and Printing QR Codes',
        titleHi: 'QR कोड बनाना और प्रिंट करना',
        duration: '7:25',
        youtubeIds: same('5Q2_m5EVdOE'),
        description: 'How to generate a QR code for your batch and attach it to wool bales for buyers and inspectors.',
      },
      {
        id: 'qr-4',
        title: 'Scanning QR Codes to Verify Wool',
        titleHi: 'ऊन की जांच के लिए QR कोड स्कैन करना',
        duration: '5:50',
        youtubeIds: same('AozVMHVpEbw'),
        description: 'How buyers, inspectors, and consumers use QR code scanning to verify wool origin and quality.',
      },
      {
        id: 'qr-5',
        title: 'Linking Quality Certificates to Your Batch',
        titleHi: 'अपने बैच से गुणवत्ता प्रमाणपत्र जोड़ना',
        duration: '8:10',
        youtubeIds: same('KPBh5MLyBd0'),
        description: 'How quality inspection results and certificates are automatically linked to your batch QR code.',
      },
    ],
    quiz: [
      {
        question: 'A Batch ID in WoolTrace follows the format:',
        questionHi: 'WoolTrace में बैच ID का फॉर्मेट क्या है?',
        options: ['WR-XXXX-YYYY', 'WT-STATE-YEAR-XXXXX', 'BATCH-001', 'QR-FARMER-ID'],
        correct: 1,
        explanation: 'WoolTrace uses the format WT-[STATE]-[YEAR]-[NUMBER] e.g., WT-RJ-2026-00123 for Rajasthan batches.',
      },
      {
        question: 'What information does a WoolTrace QR code contain?',
        questionHi: 'WoolTrace QR कोड में क्या जानकारी होती है?',
        options: ['Only the farmer\'s name', 'Farm origin, quality grade, inspection status, and transaction history', 'Just the batch weight', 'A phone number'],
        correct: 1,
        explanation: 'WoolTrace QR codes link to a full digital record including farm origin, inspection reports, quality certificates, and transaction history.',
      },
      {
        question: 'Who can scan and view a WoolTrace wool batch QR code?',
        questionHi: 'WoolTrace ऊन बैच QR कोड कौन स्कैन कर सकता है?',
        options: ['Only the farmer', 'Only quality inspectors', 'Any WoolTrace participant (buyers, inspectors, consumers)', 'Only government officials'],
        correct: 2,
        explanation: 'QR codes provide transparency — any WoolTrace participant can scan to view the batch\'s journey from farm to fabric.',
      },
      {
        question: 'When should you generate a batch QR code?',
        questionHi: 'बैच QR कोड कब बनाना चाहिए?',
        options: ['After selling the wool', 'Immediately after shearing and before any sale or inspection', 'Only when a buyer requests it', 'After processing'],
        correct: 1,
        explanation: 'Create the digital batch immediately after shearing so the full journey — inspection, sale, transport, processing — is recorded from the start.',
      },
      {
        question: 'A quality certificate is linked to your batch automatically when:',
        questionHi: 'गुणवत्ता प्रमाणपत्र आपके बैच से कब जुड़ता है?',
        options: ['You print it yourself', 'The quality inspector submits their test results in WoolTrace', 'You pay a fee online', 'After 30 days automatically'],
        correct: 1,
        explanation: 'When a certified quality inspector submits their test results in WoolTrace, the certificate is automatically linked to your batch QR.',
      },
    ],
  },
  {
    id: 'market-access',
    title: 'Market Access & Fair Pricing',
    titleHi: 'बाजार पहुंच और उचित मूल्य',
    titleGu: 'બજાર ઍક્સેસ અને ઉચિત ભાવ',
    titleMr: 'बाजार प्रवेश आणि उचित किंमत',
    titleTe: 'మార్కెట్ యాక్సెస్ మరియు న్యాయమైన ధర',
    titleTa: 'சந்தை அணுகல் & நியாயமான விலை',
    titleKn: 'ಮಾರುಕಟ್ಟೆ ಪ್ರವೇಶ ಮತ್ತು ನ್ಯಾಯ ಬೆಲೆ',
    description:
      'Read mandi price trends, compare buyer bids, understand MSP rates, and use the WoolTrace marketplace to get better returns without middlemen.',
    level: 'Intermediate',
    duration: '25 min',
    tone: 'lime',
    icon: 'TrendingUp',
    languageCount: 8,
    format: 'Interactive guide',
    progress: 0,
    lessons: [
      {
        id: 'ma-1',
        title: 'Understanding Wool Mandi Prices',
        titleHi: 'ऊन मंडी भाव समझना',
        duration: '7:30',
        youtubeIds: same('HzFiB_grPHk'),
        description: 'How wool prices are set at mandis — modal price, minimum/maximum ranges, and seasonal patterns.',
      },
      {
        id: 'ma-2',
        title: 'MSP and Government Support Prices',
        titleHi: 'MSP और सरकारी समर्थन मूल्य',
        duration: '6:45',
        youtubeIds: same('Y_Pl4dxR1sY'),
        description: 'Minimum Support Prices for wool, CWDB procurement schemes, and how to claim MSP benefits.',
      },
      {
        id: 'ma-3',
        title: 'Using WoolTrace Marketplace to Sell',
        titleHi: 'बेचने के लिए WoolTrace मार्केटप्लेस का उपयोग',
        duration: '8:20',
        youtubeIds: same('IHFovmN9G-k'),
        description: 'How to list your wool batch on the WoolTrace marketplace and receive competitive buyer bids.',
      },
      {
        id: 'ma-4',
        title: 'Reverse Bidding: Getting the Best Price',
        titleHi: 'रिवर्स बिडिंग: सबसे अच्छी कीमत पाना',
        duration: '5:15',
        youtubeIds: same('Hq6f1eQNaP4'),
        description: 'How the reverse bidding system works — buyers compete to offer you the best price for your quality wool.',
      },
    ],
    quiz: [
      {
        question: 'MSP stands for:',
        questionHi: 'MSP का मतलब क्या है?',
        options: ['Market Support Plan', 'Minimum Support Price', 'Maximum Sale Price', 'Market Selling Protocol'],
        correct: 1,
        explanation: 'MSP (Minimum Support Price) is the government-guaranteed minimum price farmers receive for their agricultural produce including wool.',
      },
      {
        question: 'In the WoolTrace marketplace, "reverse bidding" means:',
        questionHi: 'WoolTrace मार्केटप्लेस में "रिवर्स बिडिंग" का मतलब है:',
        options: ['The farmer bids for buyers', 'Multiple buyers compete to offer higher prices to the farmer', 'Prices only go down in the auction', 'The government sets the price'],
        correct: 1,
        explanation: 'In reverse bidding, multiple buyers compete to win your wool lot, which drives prices up in the farmer\'s favor.',
      },
      {
        question: 'Modal price at a mandi refers to:',
        questionHi: 'मंडी में मोडल मूल्य का मतलब है:',
        options: ['The highest price ever recorded', 'The most frequently traded price on a given day', 'The government guaranteed price', 'The lowest price of the day'],
        correct: 1,
        explanation: 'Modal price is the most frequently traded price at a mandi on a given day — the best indicator of the real market rate.',
      },
      {
        question: 'Why is quality grading important for market access?',
        questionHi: 'बाजार पहुंच के लिए गुणवत्ता ग्रेडिंग क्यों जरूरी है?',
        options: ['It makes wool heavier', 'Graded, certified wool gets higher prices and more buyer interest', 'It reduces transport costs', 'Buyers don\'t care about grading'],
        correct: 1,
        explanation: 'Certified, graded wool removes buyer uncertainty and allows farmers to command premium prices over ungraded lots.',
      },
      {
        question: 'What is the main benefit of selling through WoolTrace instead of a local trader?',
        questionHi: 'स्थानीय व्यापारी की बजाय WoolTrace से बेचने का मुख्य फायदा क्या है?',
        options: ['Faster transport', 'Direct access to more buyers, competitive pricing, and transparent transactions', 'Easier paperwork', 'Lower wool weight requirement'],
        correct: 1,
        explanation: 'WoolTrace marketplace gives you access to more buyers, transparent pricing, and eliminates middlemen who take a large commission.',
      },
    ],
  },
];
