// WoolTrace Academy - module and playlist data.
// Video titles and IDs are aligned with Australian Wool Innovation training resources.

const same = (id) => ({
  en: id,
  hi: id,
  gu: id,
  raj: id,
  ta: id,
  te: id,
  kn: id,
  mr: id,
  bn: id,
  pa: id,
  ur: id,
  ks: id,
});

export const moduleData = [
  {
    id: 'shearing',
    title: 'Novice Shearing Foundations',
    titleHi: 'नए कतराई करने वालों के लिए आधार',
    titleGu: 'નવા કાતરનાર માટે પાયો',
    titleMr: 'नवीन कातरणाऱ्यांसाठी पायाभूत प्रशिक्षण',
    titleTe: 'కొత్త కత్తిరింపుదారుల పునాది',
    titleTa: 'புதிய கத்தரிப்பாளர்களுக்கான அடித்தளம்',
    titleKn: 'ಹೊಸ ಕತ್ತರಿಸುವವರಿಗೆ ಮೂಲಭೂತ ತರಬೇತಿ',
    description:
      'Build the core shearing routine: body position, board setup, handpiece preparation, and the main blows used to remove fleece cleanly.',
    level: 'Beginner',
    duration: '48 min',
    tone: 'ivory',
    icon: 'Scissors',
    languageCount: 12,
    format: 'Video + field checklist',
    progress: 0,
    lessons: [
      {
        id: 'sh-1',
        title: 'Circle of Position',
        titleHi: 'स्थिति का चक्र',
        duration: '8:24',
        youtubeIds: same('kxsa7zATRWQ'),
        description: 'Learn the movement circle that helps a shearer stay balanced and keep control of the sheep.',
      },
      {
        id: 'sh-2',
        title: 'Clothing and Setting Up',
        titleHi: 'कपड़े और बोर्ड की तैयारी',
        duration: '6:12',
        youtubeIds: same('OqN4q0Dw_q4'),
        description: 'Set up safe clothing, footwear, and board conditions before the first sheep is brought in.',
      },
      {
        id: 'sh-3',
        title: 'Setting Up the Handpiece',
        titleHi: 'हैंडपीस तैयार करना',
        duration: '7:35',
        youtubeIds: same('MmV7eBOM6uw'),
        description: 'Check the comb, cutter, tension, and lubrication so the handpiece cuts cleanly and safely.',
      },
      {
        id: 'sh-4',
        title: 'Belly - Position and Control',
        titleHi: 'पेट की कतराई - स्थिति और नियंत्रण',
        duration: '7:50',
        youtubeIds: same('A00fNuZtLsE'),
        description: 'Practice the first belly position with calm sheep control and clear blow placement.',
      },
      {
        id: 'sh-5',
        title: 'First Hind Leg - Position and Control',
        titleHi: 'पहला पिछला पैर - स्थिति और नियंत्रण',
        duration: '8:18',
        youtubeIds: same('S69_UG6m8Mg'),
        description: 'Move from the belly to the first hind leg while keeping the sheep secure and the fleece intact.',
      },
      {
        id: 'sh-6',
        title: 'The Last Side - Position and Control',
        titleHi: 'आखिरी साइड - स्थिति और नियंत्रण',
        duration: '9:02',
        youtubeIds: same('r7WlOXo0eLE'),
        description: 'Finish the final side with steady footwork, controlled tension on the skin, and clean strokes.',
      },
    ],
    quiz: [
      {
        question: 'What is the main purpose of the circle of position?',
        questionHi: 'स्थिति के चक्र का मुख्य उद्देश्य क्या है?',
        options: ['To weigh the fleece', 'To keep the shearer balanced while controlling the sheep', 'To replace sharpening', 'To mark the wool bale'],
        correct: 1,
        explanation: 'The circle of position teaches safe footwork and body placement around the sheep.',
      },
      {
        question: 'Before shearing starts, the board and clothing should be:',
        questionHi: 'कतराई शुरू करने से पहले बोर्ड और कपड़े कैसे होने चाहिए?',
        options: ['Wet and loose', 'Clean, dry, and safe for movement', 'Covered with loose wool', 'Selected after the first sheep'],
        correct: 1,
        explanation: 'A clean dry board and correct clothing reduce slipping, contamination, and injury risk.',
      },
      {
        question: 'A handpiece setup check should include:',
        questionHi: 'हैंडपीस सेटअप में क्या जांचना चाहिए?',
        options: ['Only the power switch', 'Comb, cutter, tension, and lubrication', 'Only the handle color', 'The buyer name'],
        correct: 1,
        explanation: 'Comb, cutter, tension, and lubrication all affect clean cutting and animal safety.',
      },
      {
        question: 'Why is control important during belly and hind-leg blows?',
        questionHi: 'पेट और पिछले पैर की कतराई में नियंत्रण क्यों जरूरी है?',
        options: ['It makes the sheep heavier', 'It prevents skin cuts and keeps the fleece together', 'It removes the need for sorting', 'It changes wool color'],
        correct: 1,
        explanation: 'Good control keeps the sheep settled, protects the skin, and helps remove fleece in an orderly way.',
      },
      {
        question: 'The last side should be finished with:',
        questionHi: 'आखिरी साइड को कैसे पूरा करना चाहिए?',
        options: ['Fast random strokes', 'Steady footwork and controlled skin tension', 'Extra water on the fleece', 'A different animal handler'],
        correct: 1,
        explanation: 'Steady position and skin tension help the shearer finish cleanly without second cuts.',
      },
    ],
  },
  {
    id: 'grading',
    title: 'Wool Handling & Fleece Preparation',
    titleHi: 'ऊन संभालना और फ्लीस तैयारी',
    titleGu: 'ઊન સંભાળ અને ફ્લીસ તૈયારી',
    titleMr: 'ऊन हाताळणी आणि फ्लीस तयारी',
    titleTe: 'ఉన్ని నిర్వహణ మరియు ఫ్లీస్ సిద్ధం',
    titleTa: 'கம்பளி கையாளுதல் மற்றும் ஃப்ளீஸ் தயாரிப்பு',
    titleKn: 'ಉಣ್ಣೆ ನಿರ್ವಹಣೆ ಮತ್ತು ಫ್ಲೀಸ್ ಸಿದ್ಧತೆ',
    description:
      'Learn wool-room skills that protect clip value: board setup, fleece pickup, throwing, skirting, and pack folding.',
    level: 'Intermediate',
    duration: '35 min',
    tone: 'blue',
    icon: 'ClipboardList',
    languageCount: 12,
    format: 'Video + quiz',
    progress: 0,
    lessons: [
      {
        id: 'gr-1',
        title: 'Set Up',
        titleHi: 'सेट अप',
        duration: '6:45',
        youtubeIds: same('QNWmttXXk50'),
        description: 'Prepare the wool table, bins, broom, and workflow so the clip moves cleanly through the shed.',
      },
      {
        id: 'gr-2',
        title: 'Pick Up',
        titleHi: 'फ्लीस उठाना',
        duration: '5:20',
        youtubeIds: same('dGWqAzU3lBM'),
        description: 'Pick up a shorn fleece without dragging contamination into the main fleece line.',
      },
      {
        id: 'gr-3',
        title: 'Throw',
        titleHi: 'फ्लीस फैलाना',
        duration: '6:10',
        youtubeIds: same('sGQg3RuxdkU'),
        description: 'Throw the fleece evenly onto the table so edges, stained sections, and faults are easy to see.',
      },
      {
        id: 'gr-4',
        title: 'Skirting',
        titleHi: 'गंदे किनारे हटाना',
        duration: '8:35',
        youtubeIds: same('cstb95_v7gw'),
        description: 'Remove stained, short, or contaminated edges before the fleece is classed or packed.',
      },
      {
        id: 'gr-5',
        title: 'Pack Fold',
        titleHi: 'पैक फोल्ड',
        duration: '7:50',
        youtubeIds: same('n6zSwND5f2Y'),
        description: 'Fold prepared fleece correctly for packing, transport, and later inspection.',
      },
    ],
    quiz: [
      {
        question: 'Why is the wool-room setup completed before shearing begins?',
        questionHi: 'कतराई से पहले ऊन कक्ष की तैयारी क्यों की जाती है?',
        options: ['To slow down shearing', 'To keep fleece movement clean and organized', 'To hide stained wool', 'To avoid using a wool table'],
        correct: 1,
        explanation: 'A prepared wool room keeps clean fleece separate from oddments and contaminated wool.',
      },
      {
        question: 'When picking up fleece, the handler should avoid:',
        questionHi: 'फ्लीस उठाते समय क्या नहीं करना चाहिए?',
        options: ['Keeping it together', 'Dragging it through dirt or loose dags', 'Using both hands', 'Moving toward the table'],
        correct: 1,
        explanation: 'Dragging adds contamination and lowers the value of the fleece.',
      },
      {
        question: 'A good fleece throw helps the wool handler:',
        questionHi: 'अच्छा फ्लीस थ्रो किसमें मदद करता है?',
        options: ['See faults and edges clearly', 'Make wool wet', 'Mix all grades together', 'Skip classing'],
        correct: 0,
        explanation: 'An even throw makes it easier to identify stained edges, short wool, and faults.',
      },
      {
        question: 'Skirting means:',
        questionHi: 'स्कर्टिंग का अर्थ है:',
        options: ['Dyeing the fleece', 'Removing stained or contaminated edges', 'Weighing the sheep', 'Sharpening the cutter'],
        correct: 1,
        explanation: 'Skirting removes lower-value or contaminated edges before packing.',
      },
      {
        question: 'Pack folding is done so that fleece is:',
        questionHi: 'पैक फोल्ड क्यों किया जाता है?',
        options: ['Hidden from buyers', 'Neat, inspectable, and ready for transport', 'Mixed with oddments', 'Made heavier with moisture'],
        correct: 1,
        explanation: 'Correct folding keeps the prepared fleece tidy and easier to inspect later.',
      },
    ],
  },
  {
    id: 'nutrition',
    title: 'Shearing Safety & Animal Care',
    titleHi: 'कतराई सुरक्षा और पशु देखभाल',
    titleGu: 'કાતરણી સુરક્ષા અને પશુ સંભાળ',
    titleMr: 'कातरणी सुरक्षा आणि पशू काळजी',
    titleTe: 'కత్తిరింపు భద్రత మరియు జంతు సంరక్షణ',
    titleTa: 'கத்தரிப்பு பாதுகாப்பு மற்றும் மிருக பராமரிப்பு',
    titleKn: 'ಕತ್ತರಿಸುವ ಸುರಕ್ಷತೆ ಮತ್ತು ಪ್ರಾಣಿ ಆರೈಕೆ',
    description:
      'Focus on welfare and worker safety: catching and dragging, pressure points, vulnerable areas, and shed health practices.',
    level: 'Beginner',
    duration: '30 min',
    tone: 'lime',
    icon: 'Sprout',
    languageCount: 12,
    format: 'Video + safety quiz',
    progress: 0,
    lessons: [
      {
        id: 'sa-1',
        title: 'Catch and Drag',
        titleHi: 'पकड़ना और सुरक्षित खींचना',
        duration: '7:45',
        youtubeIds: same('DfDekDZGIgM'),
        description: 'Move sheep calmly from pen to stand while reducing stress for the animal and strain for the worker.',
      },
      {
        id: 'sa-2',
        title: 'Pressure Point',
        titleHi: 'प्रेशर पॉइंट',
        duration: '6:20',
        youtubeIds: same('Qq2KDzCkV1U'),
        description: 'Use pressure points correctly so sheep can be positioned without rough handling.',
      },
      {
        id: 'sa-3',
        title: 'Vulnerable Area',
        titleHi: 'संवेदनशील हिस्से',
        duration: '7:30',
        youtubeIds: same('xi5QvqOQVO0'),
        description: 'Recognize areas where skin folds and body shape make sheep more vulnerable to cuts.',
      },
      {
        id: 'sa-4',
        title: 'Occupational Health and Safety',
        titleHi: 'कामगार स्वास्थ्य और सुरक्षा',
        duration: '8:25',
        youtubeIds: same('Tx0PRrwKNMw'),
        description: 'Apply shed safety habits that reduce fatigue, slipping, and handling injuries.',
      },
    ],
    quiz: [
      {
        question: 'The safest catch-and-drag method aims to:',
        questionHi: 'सबसे सुरक्षित पकड़ने और खींचने की पद्धति का उद्देश्य क्या है?',
        options: ['Rush the sheep', 'Reduce stress and keep control', 'Pull by the fleece', 'Avoid checking the pen'],
        correct: 1,
        explanation: 'Calm controlled movement protects both the sheep and the worker.',
      },
      {
        question: 'Pressure points should be used to:',
        questionHi: 'प्रेशर पॉइंट का उपयोग किसलिए करना चाहिए?',
        options: ['Position sheep with less force', 'Make sheep run faster', 'Mark wool grades', 'Replace handpiece setup'],
        correct: 0,
        explanation: 'Correct pressure-point use helps position sheep without rough handling.',
      },
      {
        question: 'A vulnerable area during shearing is an area where:',
        questionHi: 'कतराई में संवेदनशील हिस्सा वह है जहां:',
        options: ['Wool has no value', 'Skin is more likely to be nicked if control is poor', 'The sheep cannot grow wool', 'Only buyers inspect'],
        correct: 1,
        explanation: 'Skin folds and sensitive body areas need slower controlled strokes.',
      },
      {
        question: 'A safe shearing shed should have:',
        questionHi: 'सुरक्षित कतराई शेड में क्या होना चाहिए?',
        options: ['Wet floors', 'Clear walkways and safe equipment', 'Loose wires across the board', 'No rest breaks'],
        correct: 1,
        explanation: 'Clear work areas and maintained equipment lower injury risk.',
      },
      {
        question: 'Worker fatigue matters because it can:',
        questionHi: 'कामगार की थकान क्यों महत्वपूर्ण है?',
        options: ['Improve accuracy', 'Increase mistakes and injury risk', 'Make wool cleaner', 'Replace training'],
        correct: 1,
        explanation: 'Tired workers are more likely to slip, lose control, or make cutting mistakes.',
      },
    ],
  },
  {
    id: 'qr-traceability',
    title: 'Quality Assurance & Market Roles',
    titleHi: 'गुणवत्ता आश्वासन और बाजार भूमिकाएं',
    titleGu: 'ગુણવત્તા ખાતરી અને બજાર ભૂમિકાઓ',
    titleMr: 'गुणवत्ता हमी आणि बाजारातील भूमिका',
    titleTe: 'నాణ్యత హామీ మరియు మార్కెట్ పాత్రలు',
    titleTa: 'தர உறுதி மற்றும் சந்தை பங்குகள்',
    titleKn: 'ಗುಣಮಟ್ಟ ಭರವಸೆ ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಪಾತ್ರಗಳು',
    description:
      'Understand how recording, branding, quality assurance, classing, growers, and buyers work together to protect clip value.',
    level: 'Advanced',
    duration: '40 min',
    tone: 'coral',
    icon: 'QrCode',
    languageCount: 12,
    format: 'Video + practice quiz',
    progress: 0,
    lessons: [
      {
        id: 'qa-1',
        title: 'Recording & Branding',
        titleHi: 'रिकॉर्डिंग और ब्रांडिंग',
        duration: '6:15',
        youtubeIds: same('0IttdxAAfjw'),
        description: 'Record clip details and brand lines clearly so wool can be identified after packing.',
      },
      {
        id: 'qa-2',
        title: 'Quality Assurance',
        titleHi: 'गुणवत्ता आश्वासन',
        duration: '8:40',
        youtubeIds: same('4awDn4rpdqw'),
        description: 'Use quality systems to reduce contamination, support inspection, and build buyer confidence.',
      },
      {
        id: 'qa-3',
        title: 'The Grower',
        titleHi: 'ऊन उत्पादक',
        duration: '7:25',
        youtubeIds: same('Tcc7s-aqZPc'),
        description: 'See the grower role in preparing sheep, facilities, documentation, and clip objectives.',
      },
      {
        id: 'qa-4',
        title: 'The Wool Classer',
        titleHi: 'ऊन क्लासर',
        duration: '8:50',
        youtubeIds: same('_AvEfq5Xujc'),
        description: 'Understand how a wool classer separates lines by type, quality, and contamination risk.',
      },
      {
        id: 'qa-5',
        title: 'The Buyer',
        titleHi: 'खरीदार',
        duration: '8:10',
        youtubeIds: same('8NAOh5v2Jv8'),
        description: 'Learn what buyers look for when assessing prepared wool and supporting records.',
      },
    ],
    quiz: [
      {
        question: 'Recording and branding help wool teams:',
        questionHi: 'रिकॉर्डिंग और ब्रांडिंग किसमें मदद करती है?',
        options: ['Lose clip identity', 'Identify lines after packing', 'Avoid preparation', 'Hide quality faults'],
        correct: 1,
        explanation: 'Clear records and branding make each wool line traceable through packing and sale.',
      },
      {
        question: 'Quality assurance is mainly used to:',
        questionHi: 'गुणवत्ता आश्वासन का मुख्य उपयोग क्या है?',
        options: ['Increase contamination', 'Create confidence through consistent preparation', 'Skip inspection', 'Make fleece wet'],
        correct: 1,
        explanation: 'Quality assurance gives buyers confidence that the clip was prepared consistently.',
      },
      {
        question: 'The wool classer decides how to:',
        questionHi: 'ऊन क्लासर क्या निर्णय लेता है?',
        options: ['Separate wool into suitable lines', 'Feed the sheep', 'Repair motors', 'Set mandi taxes'],
        correct: 0,
        explanation: 'A classer separates wool by quality, type, and faults so each line can be marketed properly.',
      },
      {
        question: 'A buyer values prepared wool because it is:',
        questionHi: 'खरीदार तैयार ऊन को क्यों महत्व देता है?',
        options: ['Easier to assess and price accurately', 'Always heavier', 'Less traceable', 'Mixed with all oddments'],
        correct: 0,
        explanation: 'Clean preparation and records make the wool easier to inspect and price.',
      },
      {
        question: 'For WoolTrace records, the best farmer habit is to:',
        questionHi: 'WoolTrace रिकॉर्ड के लिए किसान की सबसे अच्छी आदत क्या है?',
        options: ['Record clip details as work happens', 'Wait until everything is forgotten', 'Use one label for all bales', 'Skip buyer details'],
        correct: 0,
        explanation: 'Timely records keep batch identity, quality information, and market history reliable.',
      },
    ],
  },
  {
    id: 'market-access',
    title: 'Shed Setup & Clip Preparation',
    titleHi: 'शेड सेटअप और क्लिप तैयारी',
    titleGu: 'શેડ સેટઅપ અને ક્લિપ તૈયારી',
    titleMr: 'शेड सेटअप आणि क्लिप तयारी',
    titleTe: 'షెడ్ సెటప్ మరియు క్లిప్ సిద్ధం',
    titleTa: 'கொட்டகை அமைப்பு மற்றும் கிளிப் தயாரிப்பு',
    titleKn: 'ಶೆಡ್ ವ್ಯವಸ್ಥೆ ಮತ್ತು ಕ್ಲಿಪ್ ಸಿದ್ಧತೆ',
    description:
      'Prepare the shearing environment: shed layout, board setup, gates, facilities, and pen types that support clean efficient work.',
    level: 'Intermediate',
    duration: '25 min',
    tone: 'lime',
    icon: 'TrendingUp',
    languageCount: 12,
    format: 'Interactive guide',
    progress: 0,
    lessons: [
      {
        id: 'se-1',
        title: 'The Shed and Environment',
        titleHi: 'शेड और वातावरण',
        duration: '7:30',
        youtubeIds: same('27jDnoTDZIo'),
        description: 'Review the shed environment and how layout, light, cleanliness, and flow affect wool preparation.',
      },
      {
        id: 'se-2',
        title: 'Setting Up the Board',
        titleHi: 'बोर्ड सेट करना',
        duration: '6:45',
        youtubeIds: same('60DXsC26T1U'),
        description: 'Prepare the shearing board for safe movement, clean fleece handling, and steady workflow.',
      },
      {
        id: 'se-3',
        title: 'Facilities',
        titleHi: 'सुविधाएं',
        duration: '5:20',
        youtubeIds: same('EFA2B72sTsw'),
        description: 'Check the facilities needed for sheep movement, worker safety, and clean wool handling.',
      },
      {
        id: 'se-4',
        title: 'Pen Types',
        titleHi: 'पेन के प्रकार',
        duration: '5:15',
        youtubeIds: same('H9DraAEfTMI'),
        description: 'Compare pen types and how they affect sheep flow from holding areas to the shearing board.',
      },
    ],
    quiz: [
      {
        question: 'A good shed environment should support:',
        questionHi: 'अच्छा शेड वातावरण किसमें मदद करता है?',
        options: ['Clean wool flow and safe work', 'Wet fleece storage', 'Blocked walkways', 'Poor light'],
        correct: 0,
        explanation: 'Clean flow, light, and safe movement help protect wool value and worker safety.',
      },
      {
        question: 'The shearing board should be set up to:',
        questionHi: 'कतराई बोर्ड कैसे सेट होना चाहिए?',
        options: ['Allow safe movement and clean fleece handling', 'Collect dirt', 'Block sheep movement', 'Mix all wool together'],
        correct: 0,
        explanation: 'A safe board layout keeps workers moving cleanly and protects the fleece from contamination.',
      },
      {
        question: 'Facilities matter because they influence:',
        questionHi: 'सुविधाएं क्यों महत्वपूर्ण हैं?',
        options: ['Sheep flow, worker safety, and wool cleanliness', 'Only the wool color', 'Only buyer paperwork', 'Nothing in the shed'],
        correct: 0,
        explanation: 'Facilities shape how sheep, people, and wool move through the shed.',
      },
      {
        question: 'Pen types should be chosen to:',
        questionHi: 'पेन के प्रकार कैसे चुनने चाहिए?',
        options: ['Support calm sheep movement', 'Make sheep hard to catch', 'Keep wool on the floor', 'Replace classing'],
        correct: 0,
        explanation: 'Good pen design reduces stress and keeps the shearing workflow steady.',
      },
      {
        question: 'Before a learning group starts shearing practice, the trainer should check:',
        questionHi: 'कतराई अभ्यास से पहले प्रशिक्षक को क्या जांचना चाहिए?',
        options: ['Only attendance', 'Board setup, facilities, and safe sheep flow', 'Only video sound', 'Only payment status'],
        correct: 1,
        explanation: 'The practical environment must be safe and organized before farmers begin hands-on training.',
      },
    ],
  },
  {
    id: 'shearing-tips',
    title: 'Shearing Tips & Common Mistakes',
    titleHi: 'कतराई सुझाव और आम गलतियां',
    titleGu: 'કાતરણી સૂચનો અને સામાન્ય ભૂલો',
    titleMr: 'कातरणी टिप्स आणि सामान्य चुका',
    titleTe: 'కత్తిరింపు సూచనలు మరియు సాధారణ తప్పులు',
    titleTa: 'கத்தரிப்பு குறிப்புகள் மற்றும் பொதுவான தவறுகள்',
    titleKn: 'ಕತ್ತರಿಸುವ ಸಲಹೆಗಳು ಮತ್ತು ಸಾಮಾನ್ಯ ತಪ್ಪುಗಳು',
    description:
      'Improve speed and quality by correcting common novice errors, using pressure points, and reducing drag strain.',
    level: 'Intermediate',
    duration: '27 min',
    tone: 'blue',
    icon: 'Scissors',
    languageCount: 12,
    format: 'Video drills + quiz',
    progress: 0,
    lessons: [
      {
        id: 'st-1',
        title: 'Position and Control Tips',
        titleHi: 'स्थिति और नियंत्रण सुझाव',
        duration: '6:20',
        youtubeIds: same('672EKqH8bMw'),
        description: 'Sharpen body placement and sheep control so every blow starts from a stable position.',
      },
      {
        id: 'st-2',
        title: 'Novice Mistakes',
        titleHi: 'नए कतराई करने वालों की गलतियां',
        duration: '6:50',
        youtubeIds: same('9E3sqNslvJg'),
        description: 'Spot the mistakes that lead to second cuts, poor flow, animal stress, and slower shearing.',
      },
      {
        id: 'st-3',
        title: 'Catch and Drag',
        titleHi: 'पकड़ना और सुरक्षित खींचना',
        duration: '7:45',
        youtubeIds: same('DfDekDZGIgM'),
        description: 'Practice calm movement from pen to stand while protecting the sheep and the shearer.',
      },
      {
        id: 'st-4',
        title: 'Pressure Point',
        titleHi: 'प्रेशर पॉइंट',
        duration: '6:10',
        youtubeIds: same('Qq2KDzCkV1U'),
        description: 'Use pressure points to guide position with less force and more control.',
      },
    ],
    quiz: [
      {
        question: 'Most novice mistakes can be reduced by improving:',
        questionHi: 'अधिकतर शुरुआती गलतियां किससे कम होती हैं?',
        options: ['Body position and sheep control', 'Fleece moisture', 'Random stroke speed', 'Bale labels only'],
        correct: 0,
        explanation: 'Stable position and calm control are the base for clean shearing.',
      },
      {
        question: 'Second cuts usually lower value because they:',
        questionHi: 'सेकंड कट्स मूल्य क्यों घटाते हैं?',
        options: ['Create short fiber pieces', 'Improve staple length', 'Remove dirt automatically', 'Make wool brighter'],
        correct: 0,
        explanation: 'Second cuts create short pieces that reduce processing value.',
      },
      {
        question: 'Catch and drag should be done:',
        questionHi: 'पकड़ना और खींचना कैसे करना चाहिए?',
        options: ['Calmly with controlled movement', 'By pulling the fleece', 'As fast as possible', 'Only after wetting the sheep'],
        correct: 0,
        explanation: 'Calm movement protects animal welfare and worker safety.',
      },
      {
        question: 'Pressure points help a shearer:',
        questionHi: 'प्रेशर पॉइंट किसमें मदद करते हैं?',
        options: ['Use less force while positioning sheep', 'Skip board setup', 'Change wool grade', 'Avoid checking equipment'],
        correct: 0,
        explanation: 'Correct pressure-point use makes positioning smoother and safer.',
      },
      {
        question: 'A practical way to improve shearing quality is to:',
        questionHi: 'कतराई गुणवत्ता सुधारने का व्यावहारिक तरीका क्या है?',
        options: ['Practice one controlled movement at a time', 'Mix all fleece together', 'Ignore handpiece setup', 'Work on wet floors'],
        correct: 0,
        explanation: 'Focused practice builds repeatable movement and fewer errors.',
      },
    ],
  },
  {
    id: 'wool-room-oddments',
    title: 'Wool Room Oddments & Board Duties',
    titleHi: 'ऊन कक्ष ऑडमेंट्स और बोर्ड जिम्मेदारियां',
    titleGu: 'ઊન રૂમ ઓડમેન્ટ્સ અને બોર્ડ ફરજો',
    titleMr: 'ऊन रूम ऑडमेंट्स आणि बोर्ड जबाबदाऱ्या',
    titleTe: 'ఉన్ని గది ఆడ్మెంట్స్ మరియు బోర్డ్ పనులు',
    titleTa: 'கம்பளி அறை துணைப்பாகங்கள் மற்றும் போர்டு பணிகள்',
    titleKn: 'ಉಣ್ಣೆ ಕೊಠಡಿ ಒಡ್ಮೆಂಟ್ಸ್ ಮತ್ತು ಬೋರ್ಡ್ ಕರ್ತವ್ಯಗಳು',
    description:
      'Handle bellies, crutchings, broom work, board duties, and oddment preparation so clean wool stays separate.',
    level: 'Beginner',
    duration: '34 min',
    tone: 'ivory',
    icon: 'ClipboardList',
    languageCount: 12,
    format: 'Video + shed practice',
    progress: 0,
    lessons: [
      {
        id: 'wo-1',
        title: 'Broom Work',
        titleHi: 'झाड़ू और बोर्ड सफाई',
        duration: '5:40',
        youtubeIds: same('JBKNE_VzITQ'),
        description: 'Keep the board clear between sheep so clean fleece is not contaminated by scraps or dirt.',
      },
      {
        id: 'wo-2',
        title: 'Belly',
        titleHi: 'बेली ऊन',
        duration: '5:30',
        youtubeIds: same('iXZyTu9uvTg'),
        description: 'Separate belly wool correctly because it differs from the main fleece line.',
      },
      {
        id: 'wo-3',
        title: 'Crutch',
        titleHi: 'क्रचिंग ऊन',
        duration: '5:55',
        youtubeIds: same('y69YkzAdzaM'),
        description: 'Identify and prepare crutchings so stained or short wool is kept out of better lines.',
      },
      {
        id: 'wo-4',
        title: 'Board Duties',
        titleHi: 'बोर्ड जिम्मेदारियां',
        duration: '8:25',
        youtubeIds: same('m2Ki8zrHgxc'),
        description: 'Coordinate board roles so wool, oddments, and sheep movement stay organized.',
      },
      {
        id: 'wo-5',
        title: 'Oddment Preparation',
        titleHi: 'ऑडमेंट तैयारी',
        duration: '8:30',
        youtubeIds: same('QS-gJoj1z90'),
        description: 'Prepare oddments separately to protect the value of the main fleece and improve classing.',
      },
    ],
    quiz: [
      {
        question: 'Broom work protects wool value by:',
        questionHi: 'बोर्ड सफाई ऊन मूल्य कैसे बचाती है?',
        options: ['Keeping the board free of scraps and dirt', 'Adding water to fleece', 'Mixing all wool together', 'Replacing classing'],
        correct: 0,
        explanation: 'Clean board work prevents avoidable contamination.',
      },
      {
        question: 'Belly wool is usually handled separately because it:',
        questionHi: 'बेली ऊन अलग क्यों रखी जाती है?',
        options: ['Can differ from the main fleece line', 'Is always the finest line', 'Does not need inspection', 'Should be stored wet'],
        correct: 0,
        explanation: 'Belly wool commonly has different quality and contamination risk.',
      },
      {
        question: 'Crutchings should be:',
        questionHi: 'क्रचिंग ऊन को कैसे रखना चाहिए?',
        options: ['Kept out of cleaner fleece lines', 'Thrown into every bale', 'Ignored', 'Washed on the board'],
        correct: 0,
        explanation: 'Keeping crutchings separate helps protect cleaner wool lines.',
      },
      {
        question: 'Board duties are important because they:',
        questionHi: 'बोर्ड जिम्मेदारियां क्यों महत्वपूर्ण हैं?',
        options: ['Keep shed workflow organized', 'Stop sheep from growing wool', 'Remove the need for bins', 'Make labels unnecessary'],
        correct: 0,
        explanation: 'Clear roles reduce mistakes and keep wool moving through the shed correctly.',
      },
      {
        question: 'Oddment preparation should happen:',
        questionHi: 'ऑडमेंट तैयारी कब होनी चाहिए?',
        options: ['Separately from the main fleece line', 'Inside premium fleece only', 'After all labels are lost', 'Only when wool is wet'],
        correct: 0,
        explanation: 'Oddments are prepared separately so they can be classed and sold appropriately.',
      },
    ],
  },
  {
    id: 'worker-fitness',
    title: 'Shearer Fitness & Injury Prevention',
    titleHi: 'कतराई फिटनेस और चोट से बचाव',
    titleGu: 'કાતરનાર ફિટનેસ અને ઇજા નિવારણ',
    titleMr: 'कातरणाऱ्यांची फिटनेस आणि दुखापत प्रतिबंध',
    titleTe: 'కత్తిరింపుదారుల ఫిట్‌నెస్ మరియు గాయాల నివారణ',
    titleTa: 'கத்தரிப்பாளர் உடற்தகுதி மற்றும் காயம் தடுப்பு',
    titleKn: 'ಕತ್ತರಿಸುವವರ ಫಿಟ್ನೆಸ್ ಮತ್ತು ಗಾಯ ತಡೆ',
    description:
      'Reduce injury risk with warm-up habits, safe movement, recovery, and practical fitness for shearing and wool handling work.',
    level: 'Beginner',
    duration: '29 min',
    tone: 'coral',
    icon: 'Leaf',
    languageCount: 12,
    format: 'Video + wellness checklist',
    progress: 0,
    lessons: [
      {
        id: 'wf-1',
        title: 'Injury Prevention Introduction',
        titleHi: 'चोट से बचाव का परिचय',
        duration: '6:20',
        youtubeIds: same('drd6bkONdrk'),
        description: 'Understand why preparation, pacing, and recovery matter during wool harvesting.',
      },
      {
        id: 'wf-2',
        title: 'Physical Aspects',
        titleHi: 'शारीरिक पहलू',
        duration: '7:10',
        youtubeIds: same('hbxlQN6ogts'),
        description: 'Learn how posture, strength, and repeated movement affect shearer health.',
      },
      {
        id: 'wf-3',
        title: 'Wool Handling',
        titleHi: 'ऊन संभालना',
        duration: '6:40',
        youtubeIds: same('FR4cwRmxyIo'),
        description: 'Use safer lifting and movement patterns for fleece handling and wool-room work.',
      },
      {
        id: 'wf-4',
        title: 'Occupational Health and Safety',
        titleHi: 'कामगार स्वास्थ्य और सुरक्षा',
        duration: '8:25',
        youtubeIds: same('Tx0PRrwKNMw'),
        description: 'Apply worksite safety checks that reduce slips, strains, fatigue, and equipment injuries.',
      },
    ],
    quiz: [
      {
        question: 'Injury prevention begins with:',
        questionHi: 'चोट से बचाव की शुरुआत किससे होती है?',
        options: ['Preparation, pacing, and safe movement', 'Working through pain', 'Wet floors', 'Skipping rest'],
        correct: 0,
        explanation: 'Preparation and pacing reduce strain across long shearing sessions.',
      },
      {
        question: 'Repeated shearing movement affects:',
        questionHi: 'लगातार कतराई की हरकत किस पर असर डालती है?',
        options: ['Posture, strength, and fatigue', 'Only wool color', 'Only buyer records', 'Nothing'],
        correct: 0,
        explanation: 'Body mechanics and fatigue are central to worker safety.',
      },
      {
        question: 'Safe wool handling means:',
        questionHi: 'सुरक्षित ऊन संभालने का अर्थ है:',
        options: ['Using controlled lifting and movement', 'Throwing with a twisted back', 'Dragging everything on the floor', 'Ignoring table height'],
        correct: 0,
        explanation: 'Controlled movement lowers strain and keeps fleece cleaner.',
      },
      {
        question: 'A safety check should include:',
        questionHi: 'सुरक्षा जांच में क्या शामिल होना चाहिए?',
        options: ['Floor, equipment, lighting, and walkways', 'Only attendance', 'Only the buyer name', 'Only bale weight'],
        correct: 0,
        explanation: 'The worksite must be checked before practical training starts.',
      },
      {
        question: 'Rest and recovery help because they:',
        questionHi: 'आराम और रिकवरी क्यों मदद करते हैं?',
        options: ['Reduce fatigue-related mistakes', 'Make wool heavier', 'Remove the need for practice', 'Replace safety checks'],
        correct: 0,
        explanation: 'Fatigue increases mistakes, slips, and handling injuries.',
      },
    ],
  },
];
